# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 3) do

  create_table "members", :force => true do |t|
    t.column "member_num",      :integer,  :null => false
    t.column "family_name",     :string,   :null => false
    t.column "given_name",      :string,   :null => false
    t.column "furigana",        :string,   :null => false
    t.column "email",           :string
    t.column "phone",           :string
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
    t.column "login_name",      :string,   :null => false
    t.column "hashed_password", :string
    t.column "salt",            :string
    t.column "administrator",   :boolean
  end

  create_table "tasks", :force => true do |t|
    t.column "title",       :string,  :null => false
    t.column "content",     :string,  :null => false
    t.column "owner_id",    :integer, :null => false
    t.column "assigner_id", :integer, :null => false
    t.column "deadline",    :date,    :null => false
    t.column "status",      :string,  :null => false
    t.column "priority",    :integer, :null => false
    t.column "created_at",  :date,    :null => false
    t.column "updated_at",  :date,    :null => false
  end

end
